#!/bin/bash
# Critical Task Notification System
# Usage: ./notify-critical.sh <chain_id>
# Automatically called when CRITICAL priority tasks are created/updated

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHAINS_DIR="$(dirname "$SCRIPT_DIR")/communication/task-chains"
ACTIVE_DIR="$CHAINS_DIR/active"
NOTIFICATIONS_DIR="$CHAINS_DIR/notifications"

# Colors for output
RED='\033[0;31m'
BRIGHT_RED='\033[91m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Create notifications directory if it doesn't exist
mkdir -p "$NOTIFICATIONS_DIR"

# Validate arguments
if [[ $# -ne 1 ]]; then
    echo -e "${RED}Usage: $0 <chain_id>${NC}"
    exit 1
fi

CHAIN_ID="$1"
CHAIN_FILE="$ACTIVE_DIR/$CHAIN_ID.yaml"

# Check if chain file exists
if [ ! -f "$CHAIN_FILE" ]; then
    echo -e "${RED}Error: Chain file not found: $CHAIN_FILE${NC}"
    exit 1
fi

# Check if task is actually CRITICAL priority
PRIORITY=$(python3 << EOF
import yaml
with open('$CHAIN_FILE', 'r') as f:
    chain = yaml.safe_load(f)

# Get priority - handle both new 'priority' field and legacy variables
priority = chain.get('priority', 'MEDIUM').upper()
if priority == 'MEDIUM':
    # Check if there's a priority_level in variables (legacy format)
    variables = chain.get('variables', {})
    priority_level = variables.get('priority_level', '')
    if 'Critical' in priority_level or 'CRITICAL' in priority_level:
        priority = 'CRITICAL'

print(priority)
EOF
)

if [ "$PRIORITY" != "CRITICAL" ]; then
    echo -e "${YELLOW}Task $CHAIN_ID is not CRITICAL priority ($PRIORITY). No notifications sent.${NC}"
    exit 0
fi

echo -e "${BRIGHT_RED}🚨 CRITICAL PRIORITY TASK DETECTED: $CHAIN_ID${NC}"

# Get task details for notification
TASK_INFO=$(python3 << EOF
import yaml
import datetime

with open('$CHAIN_FILE', 'r') as f:
    chain = yaml.safe_load(f)

title = chain.get('title', 'Untitled Task')
description = chain.get('description', 'No description available')
created_by = chain.get('created_by', 'Unknown')

# Find all assigned Claudes in the chain
assigned_claudes = set()
for phase in chain.get('phases', []):
    assigned_to = phase.get('assigned_to', '')
    if assigned_to.startswith('claude-'):
        assigned_claudes.add(assigned_to)

# Add the chain creator if it's a Claude
if created_by.startswith('claude-'):
    assigned_claudes.add(created_by)

print(f"TITLE:{title}")
print(f"DESCRIPTION:{description}")
print(f"CREATED_BY:{created_by}")
print(f"ASSIGNED_CLAUDES:{','.join(sorted(assigned_claudes))}")
EOF
)

# Parse task info
TITLE=$(echo "$TASK_INFO" | grep "^TITLE:" | cut -d: -f2-)
DESCRIPTION=$(echo "$TASK_INFO" | grep "^DESCRIPTION:" | cut -d: -f2-)
CREATED_BY=$(echo "$TASK_INFO" | grep "^CREATED_BY:" | cut -d: -f2-)
ASSIGNED_CLAUDES=$(echo "$TASK_INFO" | grep "^ASSIGNED_CLAUDES:" | cut -d: -f2-)

echo -e "${BLUE}Task Title: ${NC}$TITLE"
echo -e "${BLUE}Created By: ${NC}$CREATED_BY"

# Create notification file for each relevant Claude
TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
NOTIFICATION_ID="critical-$CHAIN_ID-$TIMESTAMP"

# Determine which Claudes to notify based on task content and assignments
NOTIFY_CLAUDES=""

# Always notify Architect (Claude 1) for CRITICAL tasks
NOTIFY_CLAUDES="claude-1"

# Notify assigned Claudes
if [ -n "$ASSIGNED_CLAUDES" ]; then
    for claude in $(echo "$ASSIGNED_CLAUDES" | tr ',' ' '); do
        if [[ "$claude" != "claude-1" ]]; then
            NOTIFY_CLAUDES="$NOTIFY_CLAUDES $claude"
        fi
    done
fi

# Create notification content
NOTIFICATION_CONTENT=$(cat << EOF
# 🚨 CRITICAL PRIORITY TASK NOTIFICATION

**Notification ID:** $NOTIFICATION_ID  
**Timestamp:** $(date)  
**Task Chain:** $CHAIN_ID  
**Priority:** CRITICAL  

## Task Details
**Title:** $TITLE  
**Created By:** $CREATED_BY  
**Description:** $DESCRIPTION  

## Action Required
This task has been marked as CRITICAL priority. Please:

1. **Review immediately** - Critical tasks require immediate attention
2. **Check task assignment** - Use \`./chain-status.sh $CHAIN_ID\` for details
3. **Escalate if needed** - If you discover additional risks, escalate further
4. **Coordinate with team** - Critical tasks may require cross-team coordination

## Context
Critical priority indicates:
- System-breaking issues
- Data loss potential  
- Security vulnerabilities
- Blocking failures

**This notification was automatically generated by the priority system.**

---
*Use \`./chain-status.sh $CHAIN_ID\` to view full task details*
*Use \`./update-priority.sh $CHAIN_ID <priority>\` to change priority if needed*
EOF
)

# Write notification files and log
echo "$NOTIFICATION_CONTENT" > "$NOTIFICATIONS_DIR/$NOTIFICATION_ID.md"

# Log all notifications
echo "[$(date)] CRITICAL notification: $CHAIN_ID -> Claudes: $NOTIFY_CLAUDES" >> "$NOTIFICATIONS_DIR/critical-notifications.log"

echo -e "${GREEN}✅ Critical task notifications created:${NC}"
echo -e "${BLUE}Notification File: ${NC}$NOTIFICATIONS_DIR/$NOTIFICATION_ID.md"
echo -e "${BLUE}Notified Claudes: ${NC}$NOTIFY_CLAUDES"

# Display the notification content
echo
echo -e "${BRIGHT_RED}═══════════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${BRIGHT_RED}                           CRITICAL TASK NOTIFICATION                          ${NC}"  
echo -e "${BRIGHT_RED}═══════════════════════════════════════════════════════════════════════════════${NC}"
echo
echo "$NOTIFICATION_CONTENT"
echo
echo -e "${BRIGHT_RED}═══════════════════════════════════════════════════════════════════════════════${NC}"

# Optional: Display current task status for immediate context
echo
echo -e "${BLUE}Current Task Status:${NC}"
"$SCRIPT_DIR/chain-status.sh" "$CHAIN_ID"